### ISSUE TITLE
use wp_json_encode instead of json_encode

### ISSUE THREAD

**Issue by rianrietveld** [level-level/Clarkson-Core#125]
In clarkson-core-templates.php in the function render_json
Consider the use of `wp_json_encode`  instead of `json_encode`, as this has extra sanity checks.

**Comment by NielsdeBlaauw** [comment]
We need to see if we can remove this functionality altogether, as the WordPress REST API is now mature. There is no reason to prefer the clarkson-core to how the default WordPress API works.

For now we should edit this to use wp_json_encode instead of json_encode, and add a deprecated warning to use the rest API instead.
