### ISSUE TITLE
Enable Twig caching if WP_DEBUG is disabled

### ISSUE THREAD

**Issue by jmslbam** [level-level/Clarkson-Core#132]
Should we enable this by default in Core?

**Comment by NielsdeBlaauw** [comment]
There has been a `clarkson_twig_args` filter which allows themes to set this since 0.1.0 , and there is a `clarkson_twig_environment` filter coming in 1.0.0 that allows a theme to call the `setCache` method on the environment.

This is hard to do by default, as we don't know which directories are safe to write to.
