### ISSUE TITLE
Clarkson-404 returns Clarkson_Object instead of page

### ISSUE THREAD

**Issue by marcoboekestijn** [level-level/Clarkson-Core#142]
No matter what I try.

**Comment by jmslbam** [comment]
But a 404 is not a page so this behaviour is correct.

Have you installed the clarkson-404 plugin, because then it should return a page object because that plugin gets the content of that 404 page. See https://github.com/level-level/clarkson-404/blob/master/clarkson-404.php#L47

If you want a page object, then install clarkson-404.
