### ISSUE TITLE
autoloader->extra is not filled with all available template object

### ISSUE THREAD

**Issue by NielsdeBlaauw** [level-level/Clarkson-Core#161]
Currently `clarkson_core_autoloader::load_template_objects` only looks at the template of the currently visited page. Other available objects are not found. This means that a `template_frontpage` page, with a reference to a page with the template `template_other.twig` loads a `Clarkson_Object` object instead of the expected `\template_other` object.

We need to fill the `extra` property with all available templates, as we do not know which are actually used in the page.

Possible duplicate of #142

**Comment by jmslbam** [comment]
You mean the expected PHP class template_frontpage.php?


So if I understand correctly:



   1. Create a page and select a custom page template: template_x.twig.
   Save the page.
   2. Delete the file template_x.twig from disk and Re-visit the page.


You’d expect that template_x.php would be loaded because that value is
still saved in the _template meta field?

Something like that? Otherwise please rephrase the issue?


Does the issue also occurs with the code in my PR that really uses the
WordPress value of which template it should use?

**Comment by NielsdeBlaauw** [comment]
Not quite.

The templates folder has 2 files:

```
template-x.twig
template-y.twig
```

Two objects exists for these templates:

```
wordpress-objects/template_x.php
wordpress-objects/template_y.php
```

No files are deleted in reproducing in this bug.

If we load a page with template_x.twig assigned, the method `load_template_objects()` here https://github.com/level-level/Clarkson-Core/blob/cd22f17174f9584a5cd35b464aff5f43a3d989d6/lib/clarkson-core-autoloader.php#L129  only sees template_x as an available object to put in the `extras` property. 

If `wordpress-objects/template_x.php` now calls `clarkson_core_objects::get_object()` here https://github.com/level-level/Clarkson-Core/blob/cd22f17174f9584a5cd35b464aff5f43a3d989d6/lib/clarkson-core-objects.php#L132 with a post that is assigned a template `template-y.twig`, we get a `Clarkson_Object` instead of the expected `template_y` object.

This is solved when the `extras` property contains all templates available in the theme, instead of only the only currently being visited.

The issue is unrelated to PR #145 

Hope this clears up the issue.

**Comment by jmslbam** [comment]
I should test this scenario myself on an install, because looking at the
code you referred to shows me this:


I don't see `get_object( $post )` using the `extra` variable self or any
other related methods that are used in `get_object`. `get_object` bases it
related WordPress Object on the filename which is retreived by
`get_page_template_slug` in
https://github.com/level-level/Clarkson-Core/blob/cd22f17174f9584a5cd35b464aff5f43a3d989d6/lib/clarkson-core-autoloader.php#L114.
That function is a regular WP function so no reffering to ->extra.


I’m moving right now so am a bit short on time to test it. But I do
understand the issue now better ;) thanks!


xoxo Jaime

**Comment by NielsdeBlaauw** [comment]
> I don't see `get_object( $post )` using the `extra` variable self or any
other related methods that are used in `get_object`.

The `template_y` object is not loaded because it is not found on the following line, which returns early.

https://github.com/level-level/Clarkson-Core/blob/cd22f17174f9584a5cd35b464aff5f43a3d989d6/lib/clarkson-core-autoloader.php#L165

**Comment by jmslbam** [comment]
👌🏻Got it!
