### ISSUE TITLE
Fatal error: Cannot declare class Clarkson_Core\Clarkson_Core

### ISSUE THREAD

**Issue by fabolivark** [level-level/Clarkson-Core#220]
Fatal error: Cannot declare class Clarkson_Core\Clarkson_Core, because the name is already in use in /plugins/clarkson-core/clarkson-core.php on line 23

## Description
After activated the plugin it shows an error that the class is already declared and it is because they forgot to delete the line in the composer.json file where the clarkson-core.php file is called again.

![error](https://user-images.githubusercontent.com/2761885/111707321-d425ca00-8811-11eb-9b55-624280c655c7.png)

**Comment by NielsdeBlaauw** [comment]
Hi @fabolivark,

Thanks for checking out clarkson-core. 

Since version 1.0.0 Clarkson-Core no longer supports loading from the `plugins/` or `mu-plugins/` folder. If you install the library with `composer require clarkson-core` and load the `vendor/autoload.php` file somewhere in your code (preferably as soon as possible, see the [ll-plugin-autoloader](https://github.com/level-level/ll-plugin-autoloader)) clarkson-core will be automatically registered. 

I've created a new ticket #222 to review any documentation that is available for correct installation instructions.

Let me know if this clarifies usage for you.

Cheers.
